# Generated by Django 6.0 on 2025-12-31 13:27

import houseplans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplans', '0010_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplanimage',
            name='image',
            field=models.ImageField(storage=houseplans.models.HousePlanImageStorage(), upload_to='house_plan_images/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='', help_text='e.g., South Africa, Venda'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='e.g., Cedrichouseplan@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='e.g., 0695885837', max_length=20),
        ),
    ]
