# Generated by Django 6.0 on 2025-12-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplans', '0011_alter_houseplanimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='yoco_reference',
            field=models.CharField(blank=True, help_text='Yoco payment reference ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='yoco_token',
            field=models.CharField(blank=True, help_text='Yoco payment token', max_length=255, null=True),
        ),
    ]
