# Generated by Django 6.0 on 2026-02-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplans', '0013_sitesettings_home_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='yoco_checkout_id',
            field=models.CharField(blank=True, help_text='Yoco checkout session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='yoco_payment_id',
            field=models.CharField(blank=True, help_text='Yoco payment ID', max_length=255, null=True),
        ),
    ]
