# Generated by Django 6.0 on 2026-02-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseplans', '0013_purchase_secret_password_hash'),
        ('houseplans', '0015_purchase_public_id'),
    ]

    operations = [
    ]
